AWSTemplateFormatVersion: "2010-09-09"

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: sam-api.stevecshanks.dev
      WebsiteConfiguration:
        IndexDocument: index.html
Outputs:
  WebsiteURL:
    Value: !GetAtt
      - WebsiteBucket
      - WebsiteURL
