version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2tzvqn7s2pse"
s3_prefix = "sam-api"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
