version: 2.1

orbs:
  sam: circleci/aws-sam-serverless@2.1.0

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8.6
    steps:
      - checkout
      - run: touch .python.installed
      - run: make lint
      - run: make test
  deploy:
    executor: sam/default
    steps:
      - sam/install
      - checkout
      - run: make deploy

workflows:
  main:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
