version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8.6
    steps:
      - checkout
      - run: touch .python.installed
      - run: make lint
      - run: make test

workflows:
  main:
    jobs:
      - build-and-test
